# Use postgres/example user/password credentials
version: '3.1'

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/opt --lower-case-table-names=1
    restart: always
    ports:
      - 33060:33060
      - 3306:3306
    volumes:
      - ./tpch_load_data_test:/opt
      - ./tpch_load_data_test/load.sh:/docker-entrypoint-initdb.d/load.sh
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mysql

  workload:
    image: workload-executor
    depends_on:
      - mysql
    restart: always

  outertuning:
    image: outer-tuning
    restart: always
    depends_on:
      - mysql
      - workload
    ports:
    - 80:8080

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
