# Use postgres/example user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/opt --lower-case-table-names=1
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./tpch_load_data_test:/opt
      - ./tpch_load_data_test/load.sh:/docker-entrypoint-initdb.d/load.sh
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mysql
    security_opt:
      - seccomp:unconfined

  workload:
    image: workload-executor
    restart: on-failure
    build:
      context: ./tpch_workload_executor
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    links:
      - mysql

  outertuning:
    image: outertuning
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 80:8080